from .pacote import PacoteSerializer,PacoteListSerializer,PacoteDetailSerializer
from .cliente import ClienteSerializer, ClienteListSerializer, ClienteDetailSerializer
from .pacoteprocesso import PacotesProcessoSerializer
from .procedimento import  ProcedimentoSerializer, ProcedimentoListSerializer, ProcedimentoDetailSerializer
from .agendamento import AgendamentoSerializer