# Generated by Django 4.2.5 on 2023-09-06 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                (
                    "cpf",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="CPF"
                    ),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=55, verbose_name="endereço"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="e-mail"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pacote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=100)),
                (
                    "preco",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("status", models.CharField(max_length=100)),
                (
                    "imagem",
                    models.ManyToManyField(related_name="+", to="uploader.image"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Procedimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=100)),
                (
                    "preco",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("status", models.CharField(max_length=100)),
                (
                    "imagem",
                    models.ManyToManyField(related_name="+", to="uploader.image"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PacotesProcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField(default=0, null=True)),
                (
                    "pacote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="PacotesProcesso",
                        to="estetica.pacote",
                    ),
                ),
                (
                    "procedimento",
                    models.ManyToManyField(
                        related_name="+", to="estetica.procedimento"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_hora", models.DateField(blank=True, null=True)),
                ("confirmacao", models.CharField(max_length=100)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Agendamento",
                        to="estetica.cliente",
                    ),
                ),
                (
                    "procedimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Agendamento",
                        to="estetica.procedimento",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Agendamentos",
            },
        ),
    ]
